import type { AnalysisBackend } from './AnalysisBackend';
import type {
  AnalysisResult, Caps, CsvMeta, EventOverride, EventRecord,
  MetricSeries, SnapshotData, SnapshotOpts,
} from './types';
import sampleResult from '../dev/sample_result.json';
import sampleMeta from '../dev/sample_meta.json';
import sampleSnapshots from '../dev/sample_snapshots.json';

const RESULT = sampleResult as unknown as AnalysisResult;
const META = sampleMeta as unknown as CsvMeta;
const SNAPSHOTS = sampleSnapshots as unknown as SnapshotData[];

/**
 * Browser-only dev backend. Serves the committed sample (generated by
 * `web/scripts/gen_sample.py` from the real engine) so the UI runs in a plain
 * browser with no PyWebview and no server. Never used in the packaged app.
 */
export class MockBackend implements AnalysisBackend {
  async caps(): Promise<Caps> {
    return { platform: 'mock', canReport: false, canXls: false };
  }

  async loadCsv(_file: File): Promise<CsvMeta> {
    return META;
  }

  async runAnalysis(_config: Record<string, unknown> = {}): Promise<AnalysisResult> {
    return RESULT;
  }

  async metricSeries(column: string): Promise<MetricSeries> {
    return RESULT.metrics[column];
  }

  // Mock can't recompute (no Python); returns the bundled snapshot / unchanged events.
  async snapshot(index: number, _opts: SnapshotOpts = {}): Promise<SnapshotData> {
    return SNAPSHOTS[index];
  }

  async recalc(_overrides: Record<number, EventOverride>): Promise<{ events: EventRecord[] }> {
    return { events: RESULT.events };
  }
}
