import type { AnalysisBackend } from './AnalysisBackend';
import type {
  AnalysisResult, Caps, CsvMeta, EcuRecording, EventOverride, EventRecord,
  IticData, MetricSeries, ReportRequest, ReportResult, SettingsReference,
  SetpointOptions, SetpointResult, SnapshotData, SnapshotOpts, SteadyResult, SteadyWindowEdit,
  TemplateInfo,
} from './types';
import sampleResult from '../dev/sample_result.json';
import sampleMeta from '../dev/sample_meta.json';
import sampleSnapshots from '../dev/sample_snapshots.json';
import sampleSetpoint from '../dev/sample_setpoint.json';
import sampleEcu from '../dev/sample_ecu.json';
import sampleSettings from '../dev/sample_settings.json';

const RESULT = sampleResult as unknown as AnalysisResult;
const META = sampleMeta as unknown as CsvMeta;
const SNAPSHOTS = sampleSnapshots as unknown as SnapshotData[];
const SETPOINT = sampleSetpoint as unknown as SetpointResult;
const ECU = sampleEcu as unknown as EcuRecording;
const SETTINGS = sampleSettings as unknown as SettingsReference;

/**
 * Browser-only dev backend. Serves the committed sample (generated by
 * `web/scripts/gen_sample.py` from the real engine) so the UI runs in a plain
 * browser with no PyWebview and no server. Never used in the packaged app.
 */
export class MockBackend implements AnalysisBackend {
  async caps(): Promise<Caps> {
    // Reports need host Python (matplotlib + Chromium) → off. XLS *viewing* runs
    // off committed samples, so the dev preview can demo the WinScope/Set Point/ECU
    // tabs (the file content is ignored, like loadCsv/runAnalysis already are).
    return { platform: 'mock', canReport: false, canXls: true };
  }

  async loadCsv(_file: File): Promise<CsvMeta> {
    return META;
  }

  async loadWinscope(_file: File): Promise<CsvMeta> {
    return { ...META, filename: 'winscope_sample.xls (demo)', logger_format: 'winscope' };
  }

  async runAnalysis(_config: Record<string, unknown> = {}): Promise<AnalysisResult> {
    return RESULT;
  }

  async metricSeries(column: string): Promise<MetricSeries> {
    return RESULT.metrics[column];
  }

  // Mock can't recompute (no Python); returns the bundled snapshot / unchanged events.
  async snapshot(index: number, _opts: SnapshotOpts = {}): Promise<SnapshotData> {
    return SNAPSHOTS[index];
  }

  async recalc(_overrides: Record<number, EventOverride>): Promise<{ events: EventRecord[]; itic?: IticData }> {
    return { events: RESULT.events, itic: RESULT.itic };
  }

  // Mock can't recompute (no Python); returns the bundled steady-state windows + summary.
  async recalcSteady(_windows?: SteadyWindowEdit[]): Promise<SteadyResult> {
    return { steady: RESULT.steady ?? [], steady_summary: RESULT.steady_summary };
  }

  // Reports need host Python (matplotlib + Chromium); not available in-browser.
  async generateReport(_req: ReportRequest): Promise<ReportResult> {
    throw new Error('Report generation runs in the desktop app.');
  }

  async defaultHtmlTemplate(): Promise<string> {
    return '<!-- Report templates are available in the desktop app. -->';
  }

  // The persistent template library lives host-side; the browser preview has none.
  async listTemplates(): Promise<TemplateInfo[]> {
    return [];
  }

  async saveTemplate(_file: File): Promise<TemplateInfo[]> {
    throw new Error('Word template uploads are saved in the desktop app.');
  }

  async deleteTemplate(_name: string): Promise<TemplateInfo[]> {
    return [];
  }

  async compareSetpoint(_kind: 'xls' | 'csv', _files: File[], _options?: SetpointOptions): Promise<SetpointResult> {
    return SETPOINT;
  }

  async ecuRecording(_file: File): Promise<EcuRecording> {
    return ECU;
  }

  async settingsReference(): Promise<SettingsReference> {
    return SETTINGS;
  }
}
